AppBundle\Entity\User:
  exclusion_policy: ALL
  properties:
    id:
      groups: ['user.l', 'user.s']
    firstname:
      groups: ['user.l', 'user.s']
    lastname:
      groups: ['user.l', 'user.s']
    email:
      groups: ['user.l', 'user.s']
    racquets:
      groups: ['user.l']
