AppBundle\Entity\Racquet:
  exclusion_policy: ALL
  properties:
    id:
      groups: ['racquet.l']
    staticWeight:
      groups: ['racquet.l']
    balance:
      groups: ['racquet.l']
    headSize:
      groups: ['racquet.l']
    distanceToTopString:
      groups: ['racquet.l']
    brand:
      groups: ['racquet.l']
    stringingPattern:
      groups: ['racquet.l']
    string:
      groups: ['racquet.l']
    dampener:
      groups: ['racquet.l']
    overGrip:
      groups: ['racquet.l']
