AppBundle\Entity\Racquet:
  exclusion_policy: ALL
  properties:
    id:
      groups: ['racquet.l']
    model:
      groups: ['racquet.l']
    brand:
      groups: ['racquet.l']
    string:
    string:
    string:
      groups: ['racquet.l']
    dampener:
      groups: ['racquet.l']
    overGrip:
      groups: ['racquet.l']
    user:
      groups: ['racquet.l']
